nclude <stdio.h>
#include <stdlib.h>
#include <time.h>
#include <sys/time.h>
#include <sys/resource.h>

#define N 2048
#define ZERO (double)(0.0)
#define THREE (double)(3.0)

double getrusage_sec(){
  struct rusage t;
  struct timeval tv;
  getrusage(RUSAGE_SELF, &t);
  tv = t.ru_utime;
  return tv.tv_sec + (double)tv.tv_usec*1e-6;
}

int main(){
  static int i,j,k;
  static int i1,i2,i3,j1,j2,j3,k1,k2,k3;//アンローリング用変数
  static double r_THREE = 1/THREE;//3で割るやつ 
  static double a[N][N],b[N][N],c[N][N],s;
  static double t1,t2;

  srand(1);

  for(i=0;i<N;i++){
    for(j=0;j<N;j++){
      a[i][j]=rand()/(double)RAND_MAX;
      b[i][j]=rand()/(double)RAND_MAX;
    }
  }

  t1 = getrusage_sec();


//ikjループに変更
//  for(i=0;i<N;i=i+4){//行固定
//      i1=i+1;
//          i2=i+2;
//              i3=i+3;
//
//                  for(j=0;j<N;j=j+4){
//                  	j1=j+1;
//                  		j2=j+2;
//                  			j3=j+3;
//
//                  			      c[i][j]=ZERO;
//                  			            c[i][j1]=ZERO;
//                  			                  c[i][j2]=ZERO;
//                  			                        c[i][j3]=ZERO;
//
//                  			                              c[i1][j]=ZERO;
//                  			                                    c[i1][j1]=ZERO;
//                  			                                          c[i1][j2]=ZERO;
//                  			                                                c[i1][j3]=ZERO;
//
//                  			                                                      c[i2][j]=ZERO;
//                  			                                                            c[i2][j1]=ZERO;
//                  			                                                                  c[i2][j2]=ZERO;
//                  			                                                                        c[i2][j3]=ZERO;
//
//                  			                                                                              c[i3][j]=ZERO;
//                  			                                                                                    c[i3][j1]=ZERO;
//                  			                                                                                          c[i3][j2]=ZERO;
//                  			                                                                                                c[i3][j3]=ZERO;
//
//                  			                                                                                                    }
//
//                  			                                                                                                        for(k=0;k<N;k=k+4){
//                  			                                                                                                        	k1=k+1;
//                  			                                                                                                        		k2=k+2;
//                  			                                                                                                        			k3=k+3;
//
//
//                  			                                                                                                        			        for(j=0;j<N;j=j+4){//アンローリング
//                  			                                                                                                        			        	    j1=j+1;
//                  			                                                                                                        			        	    	    j2=j+2;
//                  			                                                                                                        			        	    	         	    j3=j+3;
//
//                  			                                                                                                        			        	    	         	    	    c[i][j]=c[i][j]+a[i][k]*b[k][j];//行方向アクセス
//                  			                                                                                                        			        	    	         	    	                c[i][j1]=c[i][j1]+a[i][k]*b[k][j1];//行方向アクセス
//                  			                                                                                                        			        	    	         	    	                            c[i][j2]=c[i][j2]+a[i][k]*b[k][j2];//行方向アクセス
//                  			                                                                                                        			        	    	         	    	                                        c[i][j3]=c[i][j3]+a[i][k]*b[k][j3];//行方向アクセス
//
//                  			                                                                                                        			        	    	         	    	                                                    c[i][j]=c[i][j]+a[i][k1]*b[k1][j];//行方向アクセス
//                  			                                                                                                        			        	    	         	    	                                                                c[i][j1]=c[i][j1]+a[i][k1]*b[k1][j1];//行方向アクセス
//                  			                                                                                                        			        	    	         	    	                                                                            c[i][j2]=c[i][j2]+a[i][k1]*b[k1][j2];//行方向アクセス
//                  			                                                                                                        			        	    	         	    	                                                                                        c[i][j3]=c[i][j3]+a[i][k1]*b[k1][j3];//行方向アクセス
//
//                  			                                                                                                        			        	    	         	    	                                                                                                    c[i][j]=c[i][j]+a[i][k2]*b[k2][j];//行方向アクセス
//                  			                                                                                                        			        	    	         	    	                                                                                                                c[i][j1]=c[i][j1]+a[i][k2]*b[k2][j1];//行方向アクセス
//                  			                                                                                                        			        	    	         	    	                                                                                                                            c[i][j2]=c[i][j2]+a[i][k2]*b[k2][j2];//行方向アクセス
//                  			                                                                                                        			        	    	         	    	                                                                                                                                        c[i][j3]=c[i][j3]+a[i][k2]*b[k2][j3];//行方向アクセス
//
//                  			                                                                                                        			        	    	         	    	                                                                                                                                                    c[i][j]=c[i][j]+a[i][k3]*b[k3][j];//行方向アクセス
//                  			                                                                                                        			        	    	         	    	                                                                                                                                                                c[i][j1]=c[i][j1]+a[i][k3]*b[k3][j1];//行方向アクセス
//                  			                                                                                                        			        	    	         	    	                                                                                                                                                                            c[i][j2]=c[i][j2]+a[i][k3]*b[k3][j2];//行方向アクセス
//                  			                                                                                                        			        	    	         	    	                                                                                                                                                                                        c[i][j3]=c[i][j3]+a[i][k3]*b[k3][j3];//行方向アクセス
//
//
//                  			                                                                                                        			        	    	         	    	                                                                                                                                                                                                    c[i1][j]=c[i1][j]+a[i1][k]*b[k][j];//行方向アクセス
//                  			                                                                                                        			        	    	         	    	                                                                                                                                                                                                                c[i1][j1]=c[i1][j1]+a[i1][k]*b[k][j1];//行方向アクセス
//                  			                                                                                                        			        	    	         	    	                                                                                                                                                                                                                            c[i1][j2]=c[i1][j2]+a[i1][k]*b[k][j2];//行方向アクセス
//                  			                                                                                                        			        	    	         	    	                                                                                                                                                                                                                                        c[i1][j3]=c[i1][j3]+a[i1][k]*b[k][j3];//行方向アクセス
//
//                  			                                                                                                        			        	    	         	    	                                                                                                                                                                                                                                                    c[i1][j]=c[i1][j]+a[i1][k1]*b[k1][j];//行方向アクセス
//                  			                                                                                                        			        	    	         	    	                                                                                                                                                                                                                                                                c[i1][j1]=c[i1][j1]+a[i1][k1]*b[k1][j1];//行方向アクセス
//                  			                                                                                                        			        	    	         	    	                                                                                                                                                                                                                                                                            c[i1][j2]=c[i1][j2]+a[i1][k1]*b[k1][j2];//行方向アクセス
//                  			                                                                                                        			        	    	         	    	                                                                                                                                                                                                                                                                                        c[i1][j3]=c[i1][j3]+a[i1][k1]*b[k1][j3];//行方向アクセス
//
//                  			                                                                                                        			        	    	         	    	                                                                                                                                                                                                                                                                                                    c[i1][j]=c[i1][j]+a[i1][k2]*b[k2][j];//行方向アクセス
//                  			                                                                                                        			        	    	         	    	                                                                                                                                                                                                                                                                                                                c[i1][j1]=c[i1][j1]+a[i1][k2]*b[k2][j1];//行方向アクセス
//                  			                                                                                                        			        	    	         	    	                                                                                                                                                                                                                                                                                                                            c[i1][j2]=c[i1][j2]+a[i1][k2]*b[k2][j2];//行方向アクセス
//                  			                                                                                                        			        	    	         	    	                                                                                                                                                                                                                                                                                                                                        c[i1][j3]=c[i1][j3]+a[i1][k2]*b[k2][j3];//行方向アクセス
//
//                  			                                                                                                        			        	    	         	    	                                                                                                                                                                                                                                                                                                                                                    c[i1][j]=c[i1][j]+a[i1][k3]*b[k3][j];//行方向アクセス
//                  			                                                                                                        			        	    	         	    	                                                                                                                                                                                                                                                                                                                                                                c[i1][j1]=c[i1][j1]+a[i1][k3]*b[k3][j1];//行方向アクセス
//                  			                                                                                                        			        	    	         	    	                                                                                                                                                                                                                                                                                                                                                                            c[i1][j2]=c[i1][j2]+a[i1][k3]*b[k3][j2];//行方向アクセス
//                  			                                                                                                        			        	    	         	    	                                                                                                                                                                                                                                                                                                                                                                                        c[i1][j3]=c[i1][j3]+a[i1][k3]*b[k3][j3];//行方向アクセス
//
//
//                  			                                                                                                        			        	    	         	    	                                                                                                                                                                                                                                                                                                                                                                                                    c[i2][j]=c[i2][j]+a[i2][k]*b[k][j];//行方向アクセス
//                  			                                                                                                        			        	    	         	    	                                                                                                                                                                                                                                                                                                                                                                                                                c[i2][j1]=c[i2][j1]+a[i2][k]*b[k][j1];//行方向アクセス
//                  			                                                                                                        			        	    	         	    	                                                                                                                                                                                                                                                                                                                                                                                                                            c[i2][j2]=c[i2][j2]+a[i2][k]*b[k][j2];//行方向アクセス
//                  			                                                                                                        			        	    	         	    	                                                                                                                                                                                                                                                                                                                                                                                                                                        c[i2][j3]=c[i2][j3]+a[i2][k]*b[k][j3];//行方向アクセス
//
//                  			                                                                                                        			        	    	         	    	                                                                                                                                                                                                                                                                                                                                                                                                                                                    c[i2][j]=c[i2][j]+a[i2][k1]*b[k1][j];//行方向アクセス
//                  			                                                                                                        			        	    	         	    	                                                                                                                                                                                                                                                                                                                                                                                                                                                                c[i2][j1]=c[i2][j1]+a[i2][k1]*b[k1][j1];//行方向アクセス
//                  			                                                                                                        			        	    	         	    	                                                                                                                                                                                                                                                                                                                                                                                                                                                                            c[i2][j2]=c[i2][j2]+a[i2][k1]*b[k1][j2];//行方向アクセス
//                  			                                                                                                        			        	    	         	    	                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        c[i2][j3]=c[i2][j3]+a[i2][k1]*b[k1][j3];//行方向アクセス
//
//                  			                                                                                                        			        	    	         	    	                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    c[i2][j]=c[i2][j]+a[i2][k2]*b[k2][j];//行方向アクセス
//                  			                                                                                                        			        	    	         	    	                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                c[i2][j1]=c[i2][j1]+a[i2][k2]*b[k2][j1];//行方向アクセス
//                  			                                                                                                        			        	    	         	    	                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            c[i2][j2]=c[i2][j2]+a[i2][k2]*b[k2][j2];//行方向アクセス
//                  			                                                                                                        			        	    	         	    	                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        c[i2][j3]=c[i2][j3]+a[i2][k2]*b[k2][j3];//行方向アクセス
//
//                  			                                                                                                        			        	    	         	    	                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    c[i2][j]=c[i2][j]+a[i2][k3]*b[k3][j];//行方向アクセス
//                  			                                                                                                        			        	    	         	    	                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                c[i2][j1]=c[i2][j1]+a[i2][k3]*b[k3][j1];//行方向アクセス
//                  			                                                                                                        			        	    	         	    	                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            c[i2][j2]=c[i2][j2]+a[i2][k3]*b[k3][j2];//行方向アクセス
//                  			                                                                                                        			        	    	         	    	                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        c[i2][j3]=c[i2][j3]+a[i2][k3]*b[k3][j3];//行方向アクセス
//
//
//                  			                                                                                                        			        	    	         	    	                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    c[i3][j]=c[i3][j]+a[i3][k]*b[k][j];//行方向アクセス
//                  			                                                                                                        			        	    	         	    	                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                c[i3][j1]=c[i3][j1]+a[i3][k]*b[k][j1];//行方向アクセス
//                  			                                                                                                        			        	    	         	    	                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            c[i3][j2]=c[i3][j2]+a[i3][k]*b[k][j2];//行方向アクセス
//                  			                                                                                                        			        	    	         	    	                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        c[i3][j3]=c[i3][j3]+a[i3][k]*b[k][j3];//行方向アクセス
//
//                  			                                                                                                        			        	    	         	    	                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    c[i3][j]=c[i3][j]+a[i3][k1]*b[k1][j];//行方向アクセス
//                  			                                                                                                        			        	    	         	    	                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                c[i3][j1]=c[i3][j1]+a[i3][k1]*b[k1][j1];//行方向アクセス
//                  			                                                                                                        			        	    	         	    	                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            c[i3][j2]=c[i3][j2]+a[i3][k1]*b[k1][j2];//行方向アクセス
//                  			                                                                                                        			        	    	         	    	                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        c[i3][j3]=c[i3][j3]+a[i3][k1]*b[k1][j3];//行方向アクセス
//
//                  			                                                                                                        			        	    	         	    	                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    c[i3][j]=c[i3][j]+a[i3][k2]*b[k2][j];//行方向アクセス
//                  			                                                                                                        			        	    	         	    	                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                c[i3][j1]=c[i3][j1]+a[i3][k2]*b[k2][j1];//行方向アクセス
//                  			                                                                                                        			        	    	         	    	                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            c[i3][j2]=c[i3][j2]+a[i3][k2]*b[k2][j2];//行方向アクセス
//                  			                                                                                                        			        	    	         	    	                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        c[i3][j3]=c[i3][j3]+a[i3][k2]*b[k2][j3];//行方向アクセス
//
//                  			                                                                                                        			        	    	         	    	                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    c[i3][j]=c[i3][j]+a[i3][k3]*b[k3][j];//行方向アクセス
//                  			                                                                                                        			        	    	         	    	                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                c[i3][j1]=c[i3][j1]+a[i3][k3]*b[k3][j1];//行方向アクセス
//                  			                                                                                                        			        	    	         	    	                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            c[i3][j2]=c[i3][j2]+a[i3][k3]*b[k3][j2];//行方向アクセス
//                  			                                                                                                        			        	    	         	    	                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        c[i3][j3]=c[i3][j3]+a[i3][k3]*b[k3][j3];//行方向アクセス
//
//
//                  			                                                                                                        			        	    	         	    	                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                }
//                  			                                                                                                        			        	    	         	    	                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    }
//                  			                                                                                                        			        	    	         	    	                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        for(j=0;j<N;j=j+4){
//                  			                                                                                                        			        	    	         	    	                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        	j1=j+1;
//                  			                                                                                                        			        	    	         	    	                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        		j2=j+2;
//                  			                                                                                                        			        	    	         	    	                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        			j3=j+3;
//
//
//                  			                                                                                                        			        	    	         	    	                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        				c[i][j] =c[i][j]*r_THREE;//一度割るだけでいい
//                  			                                                                                                        			        	    	         	    	                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        					c[i][j1] =c[i][j1]*r_THREE;//一度割るだけでいい
//                  			                                                                                                        			        	    	         	    	                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        					        c[i][j2] =c[i][j2]*r_THREE;//一度割るだけでいい
//                  			                                                                                                        			        	    	         	    	                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        					                c[i][j3] =c[i][j3]*r_THREE;//一度割るだけでいい
//
//                  			                                                                                                        			        	    	         	    	                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        					                        c[i1][j] =c[i1][j]*r_THREE;//一度割るだけでいい
//                  			                                                                                                        			        	    	         	    	                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        					                                c[i1][j1] =c[i1][j1]*r_THREE;//一度割るだけでいい
//                  			                                                                                                        			        	    	         	    	                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        					                                        c[i1][j2] =c[i1][j2]*r_THREE;//一度割るだけでいい
//                  			                                                                                                        			        	    	         	    	                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        					                                                c[i1][j3] =c[i1][j3]*r_THREE;//一度割るだけでいい
//                  			                                                                                                        			        	    	         	    	                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        					                                                	
//                  			                                                                                                        			        	    	         	    	                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        					                                                	        c[i2][j] =c[i2][j]*r_THREE;//一度割るだけでいい
//                  			                                                                                                        			        	    	         	    	                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        					                                                	                c[i2][j1] =c[i2][j1]*r_THREE;//一度割るだけでいい
//                  			                                                                                                        			        	    	         	    	                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        					                                                	                        c[i2][j2] =c[i2][j2]*r_THREE;//一度割るだけでいい
//                  			                                                                                                        			        	    	         	    	                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        					                                                	                                c[i2][j3] =c[i2][j3]*r_THREE;//一度割るだけでいい
//
//                  			                                                                                                        			        	    	         	    	                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        					                                                	                                        c[i3][j] =c[i3][j]*r_THREE;//一度割るだけでいい
//                  			                                                                                                        			        	    	         	    	                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        					                                                	                                                c[i3][j1] =c[i3][j1]*r_THREE;//一度割るだけでいい
//                  			                                                                                                        			        	    	         	    	                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        					                                                	                                                        c[i3][j2] =c[i3][j2]*r_THREE;//一度割るだけでいい
//                  			                                                                                                        			        	    	         	    	                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        					                                                	                                                                c[i3][j3] =c[i3][j3]*r_THREE;//一度割るだけでいい
//
//                  			                                                                                                        			        	    	         	    	                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        					                                                	                                                                    }
//                  			                                                                                                        			        	    	         	    	                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        					                                                	                                                                      }
//
//                  			                                                                                                        			        	    	         	    	                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        					                                                	                                                                        t2 = getrusage_sec();
//                  			                                                                                                        			        	    	         	    	                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        					                                                	                                                                          printf("time = %10.5f\n", t2 - t1);
//
//                  			                                                                                                        			        	    	         	    	                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        					                                                	                                                                            s=ZERO;
//
//                  			                                                                                                        			        	    	         	    	                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        					                                                	                                                                              for(i=0;i<N;i+=10){
//                  			                                                                                                        			        	    	         	    	                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        					                                                	                                                                                  for(j=0;j<N;j+=10){
//                  			                                                                                                        			        	    	         	    	                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        					                                                	                                                                                        if(a[i][j]>s){
//                  			                                                                                                        			        	    	         	    	                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        					                                                	                                                                                        	s=a[i][j];
//                  			                                                                                                        			        	    	         	    	                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        					                                                	                                                                                        	      }
//                  			                                                                                                        			        	    	         	    	                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        					                                                	                                                                                        	            if(b[i][j]>s){
//                  			                                                                                                        			        	    	         	    	                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        					                                                	                                                                                        	            	s=b[i][j];
//                  			                                                                                                        			        	    	         	    	                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        					                                                	                                                                                        	            	      }
//                  			                                                                                                        			        	    	         	    	                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        					                                                	                                                                                        	            	            if(c[i][j]>s){
//                  			                                                                                                        			        	    	         	    	                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        					                                                	                                                                                        	            	            	s=c[i][j];
//                  			                                                                                                        			        	    	         	    	                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        					                                                	                                                                                        	            	            		 }
//                  			                                                                                                        			        	    	         	    	                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        					                                                	                                                                                        	            	            		     }
//                  			                                                                                                        			        	    	         	    	                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        					                                                	                                                                                        	            	            		       }
//
//                  			                                                                                                        			        	    	         	    	                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        					                                                	                                                                                        	            	            		         printf("%f\n",s);
//
//                  			                                                                                                        			        	    	         	    	                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        					                                                	                                                                                        	            	            		           return 0;
//                  			                                                                                                        			        	    	         	    	                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        					                                                	                                                                                        	            	            		           }
